[book]
authors = ["Sven Efftinge"]
multilingual = false
src = "src"
title = "Gitpod Documentation"

[output.html]
theme = "src/theme"
google-analytics = "UA-71727855-2"

[build]
build-dir = "site/doc"
create-missing = false
preprocess = ["links", "index"]

